name: mira-rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc
  - multiqc
  - snakemake=8.14.0
  - snakemake-interface-common=1.17.2
  - snakemake-interface-executor-plugins
  - snakemake-interface-report-plugins
  - snakemake-interface-storage-plugins
  - snakemake-minimal=8.14.0
  - snakemake-executor-plugin-cluster-generic=1.0.9
  - cutadapt=4.9
  - star=2.7.11b
  - qualimap=2.3
  - picard=3.3.0
  - subread=2.0.6
  - r-tidyerse=2.0.0
  - r-ggrepel=0.9.6
  - bioconductor-deseq2=1.42.0
  - r-httpgd=1.3.1